# Max weight a player can have (100%)
# You can set custom max weight for each player using permissions such as playerweight.max.100 for 100 
Max Weight: 180
Enable XP Bar: true
WeightCommand: '&6[&7PlayerWeight&6] &2Your weight is &6<weight>&2/&6<maxweight> &2(&6<weightpercent>%&2)'

Disable Messages: false

Less And Equal To:
  Percentage: 24
  SpeedPercent: 105
  Message: '&6[&7PlayerWeight&6]&a You Are Light, Nice!'
Between:
  Percentage: 25,49
  SpeedPercent: 95
  Message: '&6[&7PlayerWeight&6]&2 Getting Heavier, Be Careful!'
Between1:
  Percentage: 50,100  
  SpeedPercent: 70
  Message: '&6[&7PlayerWeight&6]&c You Are Heavy, Try to Lose Weight!'
Bigger Than:
  Percentage: 100
  SpeedPercent: 50
  Message: '&6[&7PlayerWeight&6]&4 Oh No! What Have You Done!'

# If the list of items is outdated, check here for recent item names - https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
ANVIL: 2
APPLE: 0.3
ARROW: 0.12
BAKED_POTATO: 0.4
BEACON: 0.5
BED: 2
BED_BLOCK: 0
BEDROCK: 0
BIRCH_WOOD_STAIRS: 0.5
BLAZE_POWDER: 0.1
BLAZE_ROD: 0
BOAT: 1
BONE: 0.2
BOOK: 0.14
BOOK_AND_QUILL: 0.18
BOOKSHELF: 2
BOW: 1
BOWL: 0.3
BREAD: 0.3
BREWING_STAND: 4
BREWING_STAND_ITEM: 0
BRICK: 0.2
BRICK_STAIRS: 0.6
BROWN_MUSHROOM: 0.15
BUCKET: 0.8
BURNING_FURNACE: 0
CACTUS: 0.4
CAKE: 0.5
CAKE_BLOCK: 0.5
CARPET: 0.2
CARROT: 0.1
CARROT_ITEM: 0.1
CARROT_STICK: 0.1
CAULDRON: 2
CAULDRON_ITEM: 2
CHAINMAIL_BOOTS: 1.4
CHAINMAIL_CHESTPLATE: 2.4
CHAINMAIL_HELMET: 1.4
CHAINMAIL_LEGGINGS: 1.4
CHEST: 3
CLAY: 0.5
CLAY_BALL: 0
CLAY_BRICK: 0
COAL: 0.1
COAL_BLOCK: 0.9
COAL_ORE: 0.5
COBBLE_WALL: 0.2
COBBLESTONE: 0.5
COBBLESTONE_STAIRS: 0.5
COCOA: 0.1
COMMAND: 0
COMPASS: 0
COOKED_BEEF: 0.3
COOKED_CHICKEN: 0.3
COOKED_FISH: 0.3
COOKIE: 0.1
CROPS: 0.11
DAYLIGHT_DETECTOR: 0
DEAD_BUSH: 0.1
DETECTOR_RAIL: 0
DIAMOND: 0.05
DIAMOND_AXE: 2
DIAMOND_BARDING: 1
DIAMOND_BLOCK: 1
DIAMOND_BOOTS: 2
DIAMOND_CHESTPLATE: 2
DIAMOND_HELMET: 2
DIAMOND_HOE: 1
DIAMOND_LEGGINGS: 2
DIAMOND_ORE: 0.4
DIAMOND_PICKAXE: 1.7
DIAMOND_SPADE: 1.5
DIAMOND_SWORD: 1.4
DIODE: 0
DIODE_BLOCK_OFF: 0
DIODE_BLOCK_ON: 0
DIRT: 0.5
DISPENSER: 0
DOUBLE_STEP: 0
DRAGON_EGG: 0
DROPPER: 0
EGG: 0.1
EMERALD: 0
EMERALD_BLOCK: 0
EMERALD_ORE: 0
EMPTY_MAP: 0
ENCHANTED_BOOK: 0
ENCHANTMENT_TABLE: 0
ENDER_CHEST: 0
ENDER_PEARL: 0
ENDER_PORTAL: 0
ENDER_PORTAL_FRAME: 0
ENDER_STONE: 0
EXP_BOTTLE: 0
EXPLOSIVE_MINECART: 0
EYE_OF_ENDER: 0
FEATHER: 0
FENCE: 0
FENCE_GATE: 0
FERMENTED_SPIDER_EYE: 0
FIRE: 0
FIREBALL: 0
FIREWORK: 0
FIREWORK_CHARGE: 0
FISHING_ROD: 0
FLINT: 0
FLINT_AND_STEEL: 0
FLOWER_POT: 0
FLOWER_POT_ITEM: 0
FURNACE: 2
GHAST_TEAR: 0
GLASS: 0.3
GLASS_BOTTLE: 0
GLOWING_REDSTONE_ORE: 0
GLOWSTONE: 0
GLOWSTONE_DUST: 0
GOLD_AXE: 1
GOLD_BARDING: 1
GOLD_BLOCK: 2
GOLD_BOOTS: 1.3
GOLD_CHESTPLATE: 2
GOLD_HELMET: 1.5
GOLD_HOE: 1
GOLD_INGOT: 0.3
GOLD_LEGGINGS: 1.1
GOLD_NUGGET: 0.1
GOLD_ORE: 0.5
GOLD_PICKAXE: 0.9
GOLD_PLATE: 0
GOLD_RECORD: 0
GOLD_SPADE: 0
GOLD_SWORD: 0.9
GOLDEN_APPLE: 0
GOLDEN_CARROT: 0
GRASS: 0
GRAVEL: 0.6
GREEN_RECORD: 0
GRILLED_PORK: 0.2
HARD_CLAY: 0.3
HAY_BLOCK: 0
HOPPER: 0
HOPPER_MINECART: 0
HUGE_MUSHROOM_1: 0
HUGE_MUSHROOM_2: 0
ICE: 0
INK_SACK: 0
IRON_AXE: 1.7
IRON_BARDING: 1.6
IRON_BLOCK: 3
IRON_BOOTS: 1.3
IRON_CHESTPLATE: 1.6
IRON_DOOR: 4
IRON_DOOR_BLOCK: 4
IRON_FENCE: 1.5
IRON_HELMET: 1.5
IRON_HOE: 1.2
IRON_INGOT: 1
IRON_LEGGINGS: 1.2
IRON_ORE: 1.3
IRON_PICKAXE: 1.4
IRON_PLATE: 1.3
IRON_SPADE: 1.3
IRON_SWORD: 1.6
ITEM_FRAME: 0
JACK_O_LANTERN: 0
JUKEBOX: 0
JUNGLE_WOOD_STAIRS: 0
LADDER: 0
LAPIS_BLOCK: 0
LAPIS_ORE: 0
LAVA: 0
LAVA_BUCKET: 0
LEASH: 0
LEATHER: 0.2
LEATHER_BOOTS: 0
LEATHER_CHESTPLATE: 0
LEATHER_HELMET: 0
LEATHER_LEGGINGS: 0
LEAVES: 0
LEVER: 0
LOCKED_CHEST: 0
LOG: 0.5
LONG_GRASS: 0
MAGMA_CREAM: 0
MAP: 0
MELON: 0.2
MELON_BLOCK: 0.2
MELON_SEEDS: 0.1
MELON_STEM: 0.1
MILK_BUCKET: 0
MINECART: 3
MOB_SPAWNER: 0
MONSTER_EGG: 0
MONSTER_EGGS: 0
MOSSY_COBBLESTONE: 0.4
MUSHROOM_SOUP: 0.4
MYCEL: 0
NAME_TAG: 0
NETHER_BRICK: 0.5
NETHER_BRICK_ITEM: 0.2
NETHER_BRICK_STAIRS: 0.5
NETHER_FENCE: 0.5
NETHER_STALK: 0
NETHER_STAR: 0
NETHER_WARTS: 0
NETHERRACK: 0
NOTE_BLOCK: 0
OBSIDIAN: 0.5
PAINTING: 0
PAPER: 0
PISTON_BASE: 0
PISTON_EXTENSION: 0
PISTON_MOVING_PIECE: 0
PISTON_STICKY_BASE: 0
POISONOUS_POTATO: 0
PORK: 0.3
PORTAL: 0
POTATO: 0.2
POTATO_ITEM: 0
POTION: 0.25
POWERED_MINECART: 0
POWERED_RAIL: 0
PUMPKIN: 0.1
PUMPKIN_PIE: 0
PUMPKIN_SEEDS: 0
PUMPKIN_STEM: 0
QUARTZ: 0.2
QUARTZ_BLOCK: 0.5
QUARTZ_ORE: 0.5
QUARTZ_STAIRS: 0.5
RAILS: 0.9
RAW_BEEF: 0.2
RAW_CHICKEN: 0.2
RAW_FISH: 0.1
RECORD_10: 0
RECORD_11: 0
RECORD_12: 0
RECORD_3: 0
RECORD_4: 0
RECORD_5: 0
RECORD_6: 0
RECORD_7: 0
RECORD_8: 0
RECORD_9: 0
RED_MUSHROOM: 0.2
RED_ROSE: 0
REDSTONE: 0
REDSTONE_BLOCK: 0
REDSTONE_COMPARATOR: 0
REDSTONE_COMPARATOR_OFF: 0
REDSTONE_COMPARATOR_ON: 0
REDSTONE_LAMP_OFF: 0
REDSTONE_LAMP_ON: 0
REDSTONE_ORE: 0
REDSTONE_TORCH_OFF: 0
REDSTONE_TORCH_ON: 0
REDSTONE_WIRE: 0
ROTTEN_FLESH: 0
SADDLE: 0
SAND: 0.5
SANDSTONE: 0.5
SANDSTONE_STAIRS: 0.5
SAPLING: 0
SEEDS: 0
SHEARS: 0
SIGN: 0.3
SIGN_POST: 0
SKULL: 0
SKULL_ITEM: 0
SLIME_BALL: 0
SMOOTH_BRICK: 0.5
SMOOTH_STAIRS: 0.5
SNOW: 0.5
SNOW_BALL: 0
SNOW_BLOCK: 0
SOIL: 0
SOUL_SAND: 0.5
SPECKLED_MELON: 0
SPIDER_EYE: 0
SPONGE: 0
SPRUCE_WOOD_STAIRS: 0
STAINED_CLAY: 0.3
STATIONARY_LAVA: 0
STATIONARY_WATER: 0
STEP: 0.5
STICK: 0
STONE: 0.5
STONE_AXE: 0.9
STONE_BUTTON: 0.4
STONE_HOE: 0.6
STONE_PICKAXE: 0.9
STONE_PLATE: 0.5
STONE_SPADE: 0.5
STONE_SWORD: 1.4
STORAGE_MINECART: 2
STRING: 0
SUGAR: 0
SUGAR_CANE: 0
SUGAR_CANE_BLOCK: 0
SULPHUR: 0
THIN_GLASS: 0
TNT: 0.5
TORCH: 0.1
TRAP_DOOR: 0
TRAPPED_CHEST: 0
TRIPWIRE: 0
TRIPWIRE_HOOK: 0
VINE: 0
WALL_SIGN: 0
WATCH: 0
WATER: 0
WATER_BUCKET: 0
WATER_LILY: 0
WEB: 0
WHEAT: 0
WOOD: 0.5
WOOD_AXE: 0.8
WOOD_BUTTON: 0.1
WOOD_DOOR: 0.9
WOOD_DOUBLE_STEP: 0.5
WOOD_HOE: 0.5
WOOD_PICKAXE: 0.5
WOOD_PLATE: 0.5
WOOD_SPADE: 0.5
WOOD_STAIRS: 0.5
WOOD_STEP: 0.5
WOOD_SWORD: 0.9
WOODEN_DOOR: 0.9
WOOL: 0.3
WORKBENCH: 2
WRITTEN_BOOK: 0
YELLOW_FLOWER: 0

Update Check:
  Enabled: true
  Auto Update: true
  
Config Version: 5
Debug: false